apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reminder-scheduler
  namespace: todo-app
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "*/5 * * * *"  # Every 5 minutes
    - name: route
      value: "/reminders/check"
